### ISSUE TITLE
浅谈 SDK 开发（一）五种 Mach-O 类型的凛冬之战.markdown

### ISSUE THREAD

**Issue by ValiantCat** [cbangchen/UnofficialHistory#1]
关于你的文章 这一段  
要 Embedded Library 啊。因为是不与可执行二进制文件合并的文件，需要存储在 .app/ 的 Framework/ 目录下，所以需要在 Xcode 中进行 embedded。你们也知道，动态库重点都是在链接，如果系统已经有加载了这一份相同的二进制文件，应用运行的时候就不会重新加载多一次。
审核风险。虽然也没有文档说明是禁止了动态库使用，但是总归是风险在那里，规避风险是 SDK，必须要去做的一件事情。JSPatch 出问题的时候，没有第一时间更新 SDK 的你，一定是不合格的你。

关于EmbenedLibrary这个是没有任何风险的 因为这个其实是苹果提供给你和app Extension之间共享代码的工具，而且这个文件是被系统强制在 app一启动就load的。 当然Swift也是这样的。

再举个离职，你用了AFN 你在A项目和B项目都以Embeded方式使用  那么由于签名不一样 操作系统还是会load两份(正常APP Store 途径的APP)。
所以Emebeded的使用场景一般就3中 
1. 和APP Extension共享数据
2. Swift开发(官方不支持Swift静态库) 
3. 主二进制程序__TEXTSegmentation超过系统限制 可以把部分代码分离来上线

**Comment by cbangchen** [comment]
非常感谢你对我博文的阅读和关注哈，更加感谢你对我文章中不完善的地方提出指点。
这里回答一下你提出的几个问题。
1：关于 Embeded Library，这里认为是一个劣势，主要是从 SDK 使用者的角度来看的。在我的经验里，其实比较多会遇到开发者 Link 到了 Library 之后，就报错，因为不知道 Embeded 和 Link 之间的区别，所以会有所疑问。这样的疑问一多，也是会影响工作效率。而经验稍微多一点的开发者，则不会有这样的问题。
2：文章里面我还提到了审核风险，其实我并不是说使用 Embeded Library 会出现风险，而是对动态库的使用有可能出现风险。当然，苹果只是不允许在运行时候加载可执行代码。这一点可以更改一下。
3：另外你说到了一点，Embedded Library 是苹果用来和 App Extension 共享代码的工具。其实这个选项在 Xcode5 就有了，那个时候叫做 Embedded Binaries（嵌入二进制文件），而 App Extension 则是 iOS 8 之后 才引入的插件框架。
4：你还提到了一点，就是不同的签名文件的相同动态库还是会被多次加载，这个我非常同意，我之前没有了解到这个事情，很感谢你的分享。
我会根据你提出的意见对文章进行修改，后续的文章，也希望得到你更多的关注。
谢谢，祝好。
陈超邦

**Comment by ValiantCat** [comment]
之前遇到较多动态库和静态库的问题  可以去我博客瞅一眼 我就死皮赖脸打个广告吧https://www.valiantcat.cn/

**Comment by cbangchen** [comment]
嗯嗯。这个互相学习的心态我是非常赞同的。
这里有个问题想请教一下。
在你的博客中，提到了使用源码转二进制文件的方式来做 framework 和 源码之间的动态调换。解决调试的问题。这个方式存在一个可能的问题。就是你是需要将你的代码 PUSH 到 CocoaPod 的远程仓库里面去的，对于像美团这样的公司来说，隐秘性可能也是会被考虑的比较多的一个因素，直接给出源码可能不是很安全，因为可以通过逆向获取到类名。
我们公司的业务是 SDK，但是也会需要用到组件化来分化基础库的需求，我们为了避免这种情况，采取了本地 Pod 的方式来做，但这种方式，难以避免需要多在本地维护多余的 Git 仓库。
请问是否有其他可行的解决方式呢？

**Comment by cbangchen** [comment]
可以的话，请加我的微信 fanish123，互相交流一下哈。我最喜欢加技术很好的同行了，有时候一个问题冒出脑海，真的很希望有人可以问一下。
